import { Search, MapPin, TrendingUp, TrendingDown } from "lucide-react";
import Header from "../../components/layout/Header";
import BottomTabs from "../../components/layout/BottomTabs";
import "./MandiScreen.css";
function Mandi() {
  const prices = [
    { id: 1, crop: "Mustard ( \u0938\u0930\u0938\u094B\u0902 )", mandi: "Ludhiana, Punjab", price: 5400, change: "+120", trend: "up" },
    { id: 2, crop: "Wheat ( \u0917\u0947\u0939\u0942\u0901 )", mandi: "Ludhiana, Punjab", price: 2125, change: "-45", trend: "down" },
    { id: 3, crop: "Rice ( \u091A\u093E\u0935\u0932 )", mandi: "Khanna, Punjab", price: 3450, change: "+80", trend: "up" },
    { id: 4, crop: "Maize ( \u092E\u0915\u094D\u0915\u093E )", mandi: "Jalandhar, Punjab", price: 1850, change: "+15", trend: "up" }
  ];
  return /* @__PURE__ */ React.createElement("div", { className: "screen-layout bg-muted" }, /* @__PURE__ */ React.createElement("div", { className: "screen-topbar" }, /* @__PURE__ */ React.createElement(Header, { title: "Mandi Connect", showHamburger: true })), /* @__PURE__ */ React.createElement("div", { className: "screen-body" }, /* @__PURE__ */ React.createElement("div", { className: "screen-content pb-nav" }, /* @__PURE__ */ React.createElement("div", { className: "location-bar" }, /* @__PURE__ */ React.createElement(MapPin, { size: 20, color: "var(--primary)" }), /* @__PURE__ */ React.createElement("div", { className: "loc-info" }, /* @__PURE__ */ React.createElement("span", { className: "text-sm text-muted" }, "Current Location"), /* @__PURE__ */ React.createElement("span", { className: "font-bold" }, "Ludhiana, Punjab \u25BC"))), /* @__PURE__ */ React.createElement("div", { className: "search-bar mt-4 bg-inner border-0" }, /* @__PURE__ */ React.createElement(Search, { size: 20, className: "text-muted" }), /* @__PURE__ */ React.createElement("input", { type: "text", placeholder: "Search crop or mandi..." })), /* @__PURE__ */ React.createElement("div", { className: "expert-categories mt-4" }, /* @__PURE__ */ React.createElement("button", { className: "tag active" }, "All Crops"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "My Crops"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "Favorites")), /* @__PURE__ */ React.createElement("div", { className: "mandi-list mt-4" }, prices.map((item) => /* @__PURE__ */ React.createElement("div", { key: item.id, className: "card mandi-price-card" }, /* @__PURE__ */ React.createElement("div", { className: "mandi-card-left" }, /* @__PURE__ */ React.createElement("div", { className: "crop-avatar-sm" }, item.crop.charAt(0)), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h4", null, item.crop), /* @__PURE__ */ React.createElement("p", { className: "text-muted text-sm mt-1" }, item.mandi))), /* @__PURE__ */ React.createElement("div", { className: "mandi-card-right" }, /* @__PURE__ */ React.createElement("h4", { className: "font-bold" }, "\u20B9", item.price, " ", /* @__PURE__ */ React.createElement("span", { className: "text-xs font-normal text-muted" }, "/ qtl")), /* @__PURE__ */ React.createElement("div", { className: `price-trend mt-1 ${item.trend === "up" ? "text-primary" : "text-error"}` }, item.trend === "up" ? /* @__PURE__ */ React.createElement(TrendingUp, { size: 14 }) : /* @__PURE__ */ React.createElement(TrendingDown, { size: 14 }), /* @__PURE__ */ React.createElement("span", null, item.change))))))), /* @__PURE__ */ React.createElement("div", { className: "screen-bottomnav" }, /* @__PURE__ */ React.createElement(BottomTabs, null))));
}
export {
  Mandi as default
};
