import { Search, MapPin, Filter, ShoppingCart, Star } from "lucide-react";
import Header from "../../components/layout/Header";
import BottomTabs from "../../components/layout/BottomTabs";
import "./MarketplaceScreen.css";
function Marketplace() {
  const products = [
    { id: 1, name: "DAP Fertilizer", brand: "IFFCO", price: 1350, weight: "50kg", rating: 4.8 },
    { id: 2, name: "Urea 46% N", brand: "Kribhco", price: 266, weight: "45kg", rating: 4.5 },
    { id: 3, name: "Neem Oil 10000 ppm", brand: "Kisan", price: 450, weight: "1L", rating: 4.2 },
    { id: 4, name: "Tractor Cultivator", brand: "Mahindra", price: 25e3, weight: "Equip.", rating: 4.9 }
  ];
  return /* @__PURE__ */ React.createElement("div", { className: "screen-layout bg-muted" }, /* @__PURE__ */ React.createElement("div", { className: "screen-topbar" }, /* @__PURE__ */ React.createElement(Header, { title: "Marketplace", showHamburger: true })), /* @__PURE__ */ React.createElement("div", { className: "screen-body" }, /* @__PURE__ */ React.createElement("div", { className: "screen-content pb-nav" }, /* @__PURE__ */ React.createElement("div", { className: "search-bar mt-2 bg-inner border-0" }, /* @__PURE__ */ React.createElement(Search, { size: 20, className: "text-muted" }), /* @__PURE__ */ React.createElement("input", { type: "text", placeholder: "Search seeds, fertilizers, eq..." }), /* @__PURE__ */ React.createElement(Filter, { size: 20, className: "text-primary" })), /* @__PURE__ */ React.createElement("div", { className: "expert-categories mt-4" }, /* @__PURE__ */ React.createElement("button", { className: "tag active" }, "All"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "Fertilizers"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "Seeds"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "Pesticides"), /* @__PURE__ */ React.createElement("button", { className: "tag" }, "Equipment")), /* @__PURE__ */ React.createElement("div", { className: "product-grid mt-4" }, products.map((product) => /* @__PURE__ */ React.createElement("div", { key: product.id, className: "card product-card" }, /* @__PURE__ */ React.createElement("div", { className: "product-img-ph" }, "IMG"), /* @__PURE__ */ React.createElement("div", { className: "product-details p-3" }, /* @__PURE__ */ React.createElement("p", { className: "text-xs text-muted mb-1" }, product.brand), /* @__PURE__ */ React.createElement("h4", { className: "product-title" }, product.name), /* @__PURE__ */ React.createElement("div", { className: "flex-row-between mt-2" }, /* @__PURE__ */ React.createElement("span", { className: "font-bold" }, "\u20B9", product.price), /* @__PURE__ */ React.createElement("span", { className: "text-xs text-muted bg-surface px-2 py-1 rounded" }, product.weight)), /* @__PURE__ */ React.createElement("div", { className: "flex-row-between mt-3" }, /* @__PURE__ */ React.createElement("div", { className: "flex-row items-center gap-1" }, /* @__PURE__ */ React.createElement(Star, { size: 12, color: "var(--tertiary)", className: "fill-tertiary" }), /* @__PURE__ */ React.createElement("span", { className: "text-xs" }, product.rating)), /* @__PURE__ */ React.createElement("button", { className: "btn-icon-green" }, /* @__PURE__ */ React.createElement(ShoppingCart, { size: 14 })))))))), /* @__PURE__ */ React.createElement("div", { className: "screen-bottomnav" }, /* @__PURE__ */ React.createElement(BottomTabs, null))));
}
export {
  Marketplace as default
};
