import { Search, Info, CheckCircle2, FileText, ChevronRight } from "lucide-react";
import Header from "../../components/layout/Header";
import BottomTabs from "../../components/layout/BottomTabs";
import "./SubsidyScreen.css";
function Subsidy() {
  const schemes = [
    { id: 1, title: "PM-Kisan Samman Nidhi", desc: "\u20B96,000 per year minimum income support", status: "Eligible", eligibility: "Small & Marginal Farmers" },
    { id: 2, title: "PM Fasal Bima Yojana", desc: "Crop insurance against unseen losses", status: "Pending", eligibility: "All Farmers" },
    { id: 3, title: "Kisan Credit Card (KCC)", desc: "Short-term credit limit for agricultural needs", status: "Not Applied", eligibility: "All Farmers with active Bank A/C" }
  ];
  return /* @__PURE__ */ React.createElement("div", { className: "screen-layout bg-muted" }, /* @__PURE__ */ React.createElement("div", { className: "screen-topbar" }, /* @__PURE__ */ React.createElement(Header, { title: "Subsidy Guide", showHamburger: true })), /* @__PURE__ */ React.createElement("div", { className: "screen-body" }, /* @__PURE__ */ React.createElement("div", { className: "screen-content pb-nav" }, /* @__PURE__ */ React.createElement("div", { className: "card overview-card" }, /* @__PURE__ */ React.createElement("div", { className: "flex-row-between" }, /* @__PURE__ */ React.createElement("h2", null, "Your Subsidies"), /* @__PURE__ */ React.createElement("div", { className: "circle-chart" }, /* @__PURE__ */ React.createElement("span", null, "1/3"))), /* @__PURE__ */ React.createElement("p", { className: "text-sm text-muted mt-2" }, "Active Schemes: 1 | Pending: 1")), /* @__PURE__ */ React.createElement("div", { className: "search-bar mt-4 bg-inner border-0" }, /* @__PURE__ */ React.createElement(Search, { size: 20, className: "text-muted" }), /* @__PURE__ */ React.createElement("input", { type: "text", placeholder: "Search government schemes..." })), /* @__PURE__ */ React.createElement("div", { className: "section-header mt-4" }, /* @__PURE__ */ React.createElement("h3", null, "Available Schemes")), /* @__PURE__ */ React.createElement("div", { className: "scheme-list" }, schemes.map((scheme) => /* @__PURE__ */ React.createElement("div", { key: scheme.id, className: "card scheme-card" }, /* @__PURE__ */ React.createElement("div", { className: "flex-row-between mb-2" }, /* @__PURE__ */ React.createElement("h4", { className: "flex-1" }, scheme.title), /* @__PURE__ */ React.createElement("div", { className: `status-badge ${scheme.status.toLowerCase().replace(" ", "-")}` }, scheme.status)), /* @__PURE__ */ React.createElement("p", { className: "text-sm text-muted mb-3" }, scheme.desc), /* @__PURE__ */ React.createElement("div", { className: "eligibility-box" }, /* @__PURE__ */ React.createElement(Info, { size: 14, className: "text-primary" }), /* @__PURE__ */ React.createElement("span", { className: "text-xs" }, scheme.eligibility)), /* @__PURE__ */ React.createElement("div", { className: "flex-row-between mt-4" }, /* @__PURE__ */ React.createElement("button", { className: "text-btn" }, "View Requirements"), /* @__PURE__ */ React.createElement("button", { className: "btn-primary btn-sm flex-row items-center gap-1" }, "Apply ", /* @__PURE__ */ React.createElement(ChevronRight, { size: 14 }))))))), /* @__PURE__ */ React.createElement("div", { className: "screen-bottomnav" }, /* @__PURE__ */ React.createElement(BottomTabs, null))));
}
export {
  Subsidy as default
};
